import CloudsIMG from "../assets/images/clouds.jpg";
import ClearIMG from "../assets/images/clear.jpg";
import ThunderstormIMG from "../assets/images/thunderstorm.jpg";
import RainIMG from "../assets/images/rain.jpg";
import SnowIMG from "../assets/images/snow.jpg";

import ReginaldCloudsIMG from "../assets/images/Reginald/clouds.png";
import ReginaldThunderstormIMG from "../assets/images/Reginald/clouds.png";

export const mapWeatherConditionToBackground = {
  Basic: {
    Ash: null,
    Clear: ClearIMG,
    Clouds: CloudsIMG,
    Drizzle: null,
    Dust: null,
    Fog: null,
    Haze: null,
    Mist: null,
    Rain: RainIMG,
    Sand: null,
    Smoke: null,
    Snow: SnowIMG,
    Squall: null,
    Thunderstorm: ThunderstormIMG,
    Tornado: null,
  },
  Alfeo: {
    Ash: null,
    Clear: ClearIMG,
    Clouds: CloudsIMG,
    Drizzle: null,
    Dust: null,
    Fog: null,
    Haze: null,
    Mist: null,
    Rain: RainIMG,
    Sand: null,
    Smoke: null,
    Snow: SnowIMG,
    Squall: null,
    Thunderstorm: ThunderstormIMG,
    Tornado: null,
  },
  Barok: {
    Ash: null,
    Clear: ClearIMG,
    Clouds: CloudsIMG,
    Drizzle: null,
    Dust: null,
    Fog: null,
    Haze: null,
    Mist: null,
    Rain: RainIMG,
    Sand: null,
    Smoke: null,
    Snow: SnowIMG,
    Squall: null,
    Thunderstorm: ThunderstormIMG,
    Tornado: null,
  },
  Beatrix: {
    Ash: null,
    Clear: ClearIMG,
    Clouds: CloudsIMG,
    Drizzle: null,
    Dust: null,
    Fog: null,
    Haze: null,
    Mist: null,
    Rain: RainIMG,
    Sand: null,
    Smoke: null,
    Snow: SnowIMG,
    Squall: null,
    Thunderstorm: ThunderstormIMG,
    Tornado: null,
  },
  David: {
    Ash: null,
    Clear: ClearIMG,
    Clouds: CloudsIMG,
    Drizzle: null,
    Dust: null,
    Fog: null,
    Haze: null,
    Mist: null,
    Rain: RainIMG,
    Sand: null,
    Smoke: null,
    Snow: SnowIMG,
    Squall: null,
    Thunderstorm: ThunderstormIMG,
    Tornado: null,
  },
  Ekam: {
    Ash: null,
    Clear: ClearIMG,
    Clouds: CloudsIMG,
    Drizzle: null,
    Dust: null,
    Fog: null,
    Haze: null,
    Mist: null,
    Rain: RainIMG,
    Sand: null,
    Smoke: null,
    Snow: SnowIMG,
    Squall: null,
    Thunderstorm: ThunderstormIMG,
    Tornado: null,
  },
  Isa: {
    Ash: null,
    Clear: ClearIMG,
    Clouds: CloudsIMG,
    Drizzle: null,
    Dust: null,
    Fog: null,
    Haze: null,
    Mist: null,
    Rain: RainIMG,
    Sand: null,
    Smoke: null,
    Snow: SnowIMG,
    Squall: null,
    Thunderstorm: ThunderstormIMG,
    Tornado: null,
  },
  Krit: {
    Ash: null,
    Clear: ClearIMG,
    Clouds: CloudsIMG,
    Drizzle: null,
    Dust: null,
    Fog: null,
    Haze: null,
    Mist: null,
    Rain: RainIMG,
    Sand: null,
    Smoke: null,
    Snow: SnowIMG,
    Squall: null,
    Thunderstorm: ThunderstormIMG,
    Tornado: null,
  },
  Mostafa: {
    Ash: null,
    Clear: ClearIMG,
    Clouds: CloudsIMG,
    Drizzle: null,
    Dust: null,
    Fog: null,
    Haze: null,
    Mist: null,
    Rain: RainIMG,
    Sand: null,
    Smoke: null,
    Snow: SnowIMG,
    Squall: null,
    Thunderstorm: ThunderstormIMG,
    Tornado: null,
  },
  Reginald: {
    Ash: null,
    Clear: ClearIMG,
    Clouds: ReginaldCloudsIMG,
    Drizzle: null,
    Dust: null,
    Fog: null,
    Haze: null,
    Mist: null,
    Rain: RainIMG,
    Sand: null,
    Smoke: null,
    Snow: SnowIMG,
    Squall: null,
    Thunderstorm: ReginaldThunderstormIMG,
    Tornado: null,
  },
  Tapaswini: {
    Ash: null,
    Clear: ClearIMG,
    Clouds: CloudsIMG,
    Drizzle: null,
    Dust: null,
    Fog: null,
    Haze: null,
    Mist: null,
    Rain: RainIMG,
    Sand: null,
    Smoke: null,
    Snow: SnowIMG,
    Squall: null,
    Thunderstorm: ThunderstormIMG,
    Tornado: null,
  },
  Tharun: {
    Ash: null,
    Clear: ClearIMG,
    Clouds: CloudsIMG,
    Drizzle: null,
    Dust: null,
    Fog: null,
    Haze: null,
    Mist: null,
    Rain: RainIMG,
    Sand: null,
    Smoke: null,
    Snow: SnowIMG,
    Squall: null,
    Thunderstorm: ThunderstormIMG,
    Tornado: null,
  },
  Utkaresh: {
    Ash: null,
    Clear: ClearIMG,
    Clouds: CloudsIMG,
    Drizzle: null,
    Dust: null,
    Fog: null,
    Haze: null,
    Mist: null,
    Rain: RainIMG,
    Sand: null,
    Smoke: null,
    Snow: SnowIMG,
    Squall: null,
    Thunderstorm: ThunderstormIMG,
    Tornado: null,
  },
  Victoria: {
    Ash: null,
    Clear: ClearIMG,
    Clouds: CloudsIMG,
    Drizzle: null,
    Dust: null,
    Fog: null,
    Haze: null,
    Mist: null,
    Rain: RainIMG,
    Sand: null,
    Smoke: null,
    Snow: SnowIMG,
    Squall: null,
    Thunderstorm: ThunderstormIMG,
    Tornado: null,
  },
  Zhouli: {
    Ash: null,
    Clear: ClearIMG,
    Clouds: CloudsIMG,
    Drizzle: null,
    Dust: null,
    Fog: null,
    Haze: null,
    Mist: null,
    Rain: RainIMG,
    Sand: null,
    Smoke: null,
    Snow: SnowIMG,
    Squall: null,
    Thunderstorm: ThunderstormIMG,
    Tornado: null,
  },
};
